"""addeed fields to cart item

Revision ID: 16e1061c5c3e
Revises: a03aab7fbacd
Create Date: 2024-11-29 14:06:47.043700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e1061c5c3e'
down_revision = 'a03aab7fbacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('spu', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('spu')
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('price')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
